baseurl = "https://wangzitao6.github.io" #一定要用https，github强制安全措施
title = "WangZiTao Blog"
theme = "hamburg"
languageCode = "zh_CN"
# Enable comments by entering your Disqus shortname
DisqusShortname = "WangZiTao"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/1.jpg"
  SEOTitle = "王子滔的博客 "
  description = "王子滔, 美食爱好者，生活探险家 | 这里是 王子滔 的博客，与你一起发现更大的世界。"
  keyword = "王子滔, wangzitao, WangZiTao, 王子滔的网络日志, 王子滔的博客, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Istio, Kubernetes, 微服务, Microservice"
  slogan = "~路漫漫其修远兮~"

  image_404 = "images/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""


  # Sidebar settings
  sidebar_about_description = "搬砖工程师"
  #sidebar_avatar = "images/avatar-1.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "images/me.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = "28c952e35b6e860c096a2cdf52785c6f"
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = false

  [params.social]
  rss            = false 
  email = "wang_zitao@foxmail.com" #邮箱
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github = "https://github.com/wangzitao6" #github用户名
  wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"


  
