---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "River's Site"
theme: "beautifulhugo"
metaDataFormat: "yaml"
algolia:
  index: "wangzitai-blog"
  key: "31c446dfcfdf65fe0ff50a8a68194de4"
  appID: "3DH4V2B4JK"
---
