name: github pages

on:
  push:
    branches:
      - hugo  # action触发条件，push到 hugo 分支上时触发
  pull_request:
  # 如果使用自定义域名，还需要添加下面一行配置
  #cname: www.goodfun.me

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 另外还支持 deploy_token 和 github_token
          #repository-name: wangzitao6/wangzitao6.github.io # 修改为你的 GitHub Pages 仓库
          publish_dir: ./public
          publish_branch: hugo